#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [[ -n "${MKNEXT_CHECK_LOG:-}" ]]; then
  printf 'curl %s\n' "$*" >>"$MKNEXT_CHECK_LOG"
fi

if [[ "${MKNEXT_FAKE_CURL_FAIL:-0}" == 1 ]]; then
  exit 22
fi

cat <<'INSTALLER'
#!/usr/bin/env bash
if [[ "${MKNEXT_FAKE_INSTALLER_FAIL:-0}" == 1 ]]; then
  exit 1
fi
printf 'updated\n' >"$MKNEXT_UPDATE_MARKER"
printf '%s\n' "${MKNEXT_INSTALL_PREFIX:-}" >"$MKNEXT_UPDATE_PREFIX_MARKER"
INSTALLER
